[versions]
agp = "8.4.2"
kotlin = "2.0.0"
compileSdk = "34"
minSdk = "29"
targetSdk = "34"
androidx-core-ktx = "1.13.1"
androidx-car-app = "1.7.0"
androidx-activity-compose = "1.9.1"
androidx-lifecycle-runtime-ktx = "2.8.4"
androidx-compose-bom = "2024.06.00"
androidx-compose-material3 = "1.2.1"
androidx-compose-ui-test-junit4 = "1.6.8"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
junit4 = "4.13.2"
firebase-database-ktx = "21.0.0"
ksp = "2.0.0-1.0.24"
androidx-room = "2.6.1"
kotlinx-coroutines = "1.8.1"
org-json = "20240303"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-car-app = { module = "androidx.car.app:app", version.ref = "androidx-car-app" }
androidx-car-app-automotive = { module = "androidx.car.app:app-automotive", version.ref = "androidx-car-app" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime-ktx" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose-ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
firebase-database-ktx = { module = "com.google.firebase:firebase-database-ktx", version.ref = "firebase-database-ktx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
org-json = { module = "org.json:json", version.ref = "org-json" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
jetbrains-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
