[versions]
agp = "8.4.2"
kotlin = "2.0.0"
compileSdk = "34"
minSdk = "29"
targetSdk = "34"
androidx-core-ktx = "1.13.1"
androidx-car-app = "1.7.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-car-app = { module = "androidx.car.app:app", version.ref = "androidx-car-app" }
androidx-car-app-automotive = { module = "androidx.car.app:app-automotive", version.ref = "androidx-car-app" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
